version: '3'

services:

  traefik:
    image: traefik:v2.9
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=0.0.0.0:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
      - "8080:8080"

  deezy_mostpopular:
    image: deezy_mostpopular_image:latest
    restart: always
    expose:
      - 80
    volumes:
      - ${HOME}/toponym-resolution/resources/:/app/resources/
      - ${HOME}/toponym-resolution/geoparser/:/app/geoparser/
      - ${HOME}/toponym-resolution/utils/:/app/utils/
      - ${HOME}/toponym-resolution/preprocessing/:/app/preprocessing/
      - ${HOME}/toponym-resolution/experiments/:/app/experiments/
      - ${HOME}/nltk_data:/root/nltk_data/
    labels:
      - traefik.enable=true
      - traefik.http.services.deezy_mostpopular.loadbalancer.server.port=80
      - traefik.http.routers.deezy_mostpopular_router.service=deezy_mostpopular
      - traefik.http.routers.deezy_mostpopular_router.rule=Host(`20.0.184.45`, `0.0.0.0`) && PathPrefix(`/v1/deezy_mostpopular`)
      - "traefik.http.middlewares.test-stripprefix.stripprefix.prefixes=/v1/deezy_mostpopular"
      - traefik.http.routers.deezy_mostpopular_router.middlewares=test-stripprefix
    command: ["poetry", "run", "uvicorn", "app:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]

  perfect_mostpopular:
    image: perfect_mostpopular_image:latest
    restart: always
    expose:
      - 80
    volumes:
      - ${HOME}/toponym-resolution/resources/:/app/resources/
      - ${HOME}/toponym-resolution/geoparser/:/app/geoparser/
      - ${HOME}/toponym-resolution/utils/:/app/utils/
      - ${HOME}/toponym-resolution/preprocessing/:/app/preprocessing/
      - ${HOME}/toponym-resolution/experiments/:/app/experiments/
      - ${HOME}/nltk_data:/root/nltk_data/
    labels:
      - traefik.enable=true
      - traefik.http.services.perfect_mostpopular.loadbalancer.server.port=80
      - traefik.http.routers.perfect_mostpopular_router.service=perfect_mostpopular
      - traefik.http.routers.perfect_mostpopular_router.rule=Host(`20.0.184.45`, `0.0.0.0`) && PathPrefix(`/v1/perfect_mostpopular`)
      - "traefik.http.middlewares.test-stripprefix-perfect.stripprefix.prefixes=/v1/perfect_mostpopular"
      - traefik.http.routers.perfect_mostpopular_router.middlewares=test-stripprefix-perfect
    command: ["poetry", "run", "uvicorn", "app:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]

  deezy_rel_with_publ:
    image: deezy_relwithpubl_image:latest
    restart: always
    # ports:
    #   - "8000:80"
    expose:
      - 80
    volumes:
      - ${HOME}/toponym-resolution/resources/:/app/resources/
      - ${HOME}/toponym-resolution/geoparser/:/app/geoparser/
      - ${HOME}/toponym-resolution/utils/:/app/utils/
      - ${HOME}/toponym-resolution/preprocessing/:/app/preprocessing/
      - ${HOME}/toponym-resolution/experiments/:/app/experiments/
      - ${HOME}/nltk_data:/root/nltk_data/
    labels:
      - traefik.enable=true
      - traefik.http.services.deezy_rel_with_publ.loadbalancer.server.port=80
      - traefik.http.routers.deezy_rel_with_publ_router.service=deezy_rel_with_publ
      - traefik.http.routers.deezy_rel_with_publ_router.rule=Host(`20.0.184.45`, `0.0.0.0`) && PathPrefix(`/v1/deezy_relwithpubl`)
      - "traefik.http.middlewares.test-stripprefix-rwp.stripprefix.prefixes=/v1/deezy_relwithpubl"
      - traefik.http.routers.deezy_rel_with_publ_router.middlewares=test-stripprefix-rwp
    command: ["poetry", "run", "uvicorn", "app:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]

  deezy_rel_without_publ:
    image: deezy_relwithoutpubl_image:latest
    restart: always
    expose:
      - 80
    volumes:
      - ${HOME}/toponym-resolution/resources/:/app/resources/
      - ${HOME}/toponym-resolution/geoparser/:/app/geoparser/
      - ${HOME}/toponym-resolution/utils/:/app/utils/
      - /${HOME}/toponym-resolution/preprocessing/:/app/preprocessing/
      - ${HOME}/toponym-resolution/experiments/:/app/experiments/
      - ${HOME}/nltk_data:/root/nltk_data/
    labels:
      - traefik.enable=true
      - traefik.http.services.deezy_rel_without_publ.loadbalancer.server.port=80
      - traefik.http.routers.deezy_rel_without_publ_router.service=deezy_rel_without_publ
      - traefik.http.routers.deezy_rel_without_publ_router.rule=Host(`20.0.184.45`, `0.0.0.0`) && PathPrefix(`/v1/deezy_relwithoutpubl`)
      - "traefik.http.middlewares.test-stripprefix-rwop.stripprefix.prefixes=/v1/deezy_relwithoutpubl"
      - traefik.http.routers.deezy_rel_without_publ_router.middlewares=test-stripprefix-rwop
    command: ["poetry", "run", "uvicorn", "app:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
