version: '3'

services:

  traefik:
    image: traefik:v2.9
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=0.0.0.0:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
      - "8080:8080"

  t-res_deezy_reldisamb-wpubl-wmtops:
    image: t-res_deezy_reldisamb-wpubl-wmtops_image:latest
    restart: always
    expose:
      - 80
    volumes:
      - ${HOME}/toponym-resolution/resources/:/app/resources/
      - ${HOME}/toponym-resolution/geoparser/:/app/geoparser/
      - ${HOME}/toponym-resolution/utils/:/app/utils/
      - /${HOME}/toponym-resolution/preprocessing/:/app/preprocessing/
      - ${HOME}/toponym-resolution/experiments/:/app/experiments/
      - ${HOME}/nltk_data:/root/nltk_data/
    labels:
      - traefik.enable=true
      - traefik.http.services.t-res_deezy_reldisamb-wpubl-wmtops.loadbalancer.server.port=80
      - traefik.http.routers.t-res_deezy_reldisamb-wpubl-wmtops_router.service=t-res_deezy_reldisamb-wpubl-wmtops
      - traefik.http.routers.t-res_deezy_reldisamb-wpubl-wmtops_router.rule=Host(`${HOST_URL}`, `0.0.0.0`) && PathPrefix(`/v2/t-res_deezy_reldisamb-wpubl-wmtops`)
      - "traefik.http.middlewares.test-stripprefix-reldisamb-wpubl-wmtops.stripprefix.prefixes=/v2/t-res_deezy_reldisamb-wpubl-wmtops"
      - traefik.http.routers.t-res_deezy_reldisamb-wpubl-wmtops_router.middlewares=test-stripprefix-reldisamb-wpubl-wmtops
    command: ["poetry", "run", "uvicorn", "app:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]
  