[tool.poetry]
name = "resolution"
version = "0.1.0"
description = ""
authors = ["Federico Nanni <nanni.federico@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
tqdm = "^4.62.3"
bs4 = "^0.0.1"
pandas = "^1.3.4"
wget = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
