"""
The `t_res.utils.rel_e2e` module contains utility functions for training
and running the [Radboud Entity Linker](https://github.com/informagi/REL) 
(REL) model.
"""

import json
import os
import sqlite3
import sys
from array import array
from ast import literal_eval
from typing import Any, List, Literal, Optional

import numpy as np
import pandas as pd

from ..geoparser import ranking
from .dataclasses import *

RANDOM_SEED = 42
"""Constant representing the random seed used for generating pseudo-random
numbers.

The `RANDOM_SEED` is a value that initializes the random number generator
algorithm, ensuring that the sequence of random numbers generated remains the
same across different runs of the program. This is useful for achieving
reproducibility in experiments or when consistent random behavior is
desired.

Note:
    If this docstring is changed, also make sure to edit `prepare_data.py`,
    `linking.py` and `entity_disambiguation.py`.
"""
np.random.seed(RANDOM_SEED)


def get_db_emb(
    cursor: sqlite3.Cursor,
    mentions: List[str],
    embtype: Literal["word", "entity", "snd"],
) -> List[Optional[np.ndarray]]:
    """
    Retrieve Wikipedia2Vec embeddings for a given list of words or entities.

    Arguments:
        cursor: The cursor with the open connection to the Wikipedia2Vec
            database.
        mentions (List[str]): The list of words or entities whose embeddings to
            extract.
        embtype (Literal["word", "entity", "snd"]): The type of embedding to
            retrieve. Possible values are ``"word"``, ``"entity"``, or
            ``"snd"``. If it is set to ``"word"`` or ``"snd"``, we use
            Wikipedia2Vec word embeddings, if it is set to ``"entity"``, we
            use Wikipedia2Vec entity embeddings.

    Returns:
        A list of arrays (or ``None``) representing the embeddings for the
            given mentions.

    Note:
        - The embeddings are extracted from the Wikipedia2Vec database using
          the provided cursor.
        - If the mention is an entity, the prefix ``ENTITY/`` is preappended to
          the mention before querying the database.
        - If the mention is a word, the string is converted to lowercase
          before querying the database.
        - If an embedding is not found for a mention, the corresponding
          element in the returned list is set to None.
        - Differently from the original REL implementation, we use Wikipedia2vec
          embeddings both for ``"word"`` and ``"snd"``.
    """

    results = []
    for mention in mentions:
        result = None
        # Preprocess the mention depending on which embedding to obtain:
        if embtype == "entity":
            if not mention == "#ENTITY/UNK#":
                mention = "ENTITY/" + mention
            result = cursor.execute(
                "SELECT emb FROM entity_embeddings WHERE word=?", (mention,)
            ).fetchone()
        if embtype == "word" or embtype == "snd":
            if mention in ["#WORD/UNK#", "#SND/UNK#"]:
                mention = "#WORD/UNK#"
            else:
                mention = mention.lower()
            result = cursor.execute(
                "SELECT emb FROM entity_embeddings WHERE word=?", (mention,)
            ).fetchone()
        results.append(result if result is None else array("f", result[0]).tolist())

    return results


def eval_with_exception(str2parse: str, in_case: Optional[Any] = "") -> Any:
    """
    Parse a string in the form of a list or dictionary.

    Arguments:
        str2parse (str): The string to parse.
        in_case (str, optional): The value to return in case of an error.
            Default is ``""``.

    Returns:
        The parsed value if successful, or the specified value in case of
            an error.
    """
    try:
        return literal_eval(str2parse)
    except ValueError:
        return in_case


def prepare_initial_data(df: pd.DataFrame) -> dict:
    """
    Generate the initial JSON data needed to train a REL model from a
    DataFrame.

    Arguments:
        df: The dataframe containing the linking training data.

    Returns:
        A dictionary with article IDs as keys and a list of mention
            dictionaries as values. Each mention dictionary contains
            information about a mention, excluding the "gold" field and
            candidates (at this point).

    Note:
        The DataFrame passed to this function can be generated by the
            ``experiments/prepare_data.py`` script.
    """
    dict_mentions = dict()
    for i, row in df.iterrows():
        article_id = str(row["article_id"])
        dict_sentences = dict()
        for s in eval_with_exception(row["sentences"]):
            dict_sentences[int(s["sentence_pos"])] = s["sentence_text"]

        # Build a mention dictionary per mention:
        for df_mention in eval_with_exception(row["annotations"]):
            dict_mention = dict()
            mention = df_mention["mention"]
            sent_idx = int(df_mention["sent_pos"])
            sentence_id = article_id + "_" + str(sent_idx)

            # Generate left-hand context:
            left_context = ""
            if sent_idx - 1 in dict_sentences:
                left_context = dict_sentences[sent_idx - 1]

            # Generate right-hand context:
            right_context = ""
            if sent_idx + 1 in dict_sentences:
                right_context = dict_sentences[sent_idx + 1]

            dict_mention["mention"] = df_mention["mention"]
            dict_mention["sent_idx"] = sent_idx
            dict_mention["sentence"] = dict_sentences[sent_idx]
            dict_mention["ngram"] = mention
            dict_mention["context"] = [left_context, right_context]
            dict_mention["pos"] = df_mention["mention_start"]
            dict_mention["end_pos"] = df_mention["mention_end"]
            dict_mention["place"] = row["place"]
            dict_mention["place_wqid"] = row["place_wqid"]
            dict_mention["candidates"] = []
            dict_mention["ner_label"] = df_mention["entity_type"]

            # Check this:
            dict_mention["gold"] = [df_mention["wkdt_qid"]]
            if not df_mention["wkdt_qid"].startswith("Q"):
                dict_mention["gold"] = "NIL"

            if sentence_id in dict_mentions:
                dict_mentions[sentence_id].append(dict_mention)
            else:
                dict_mentions[sentence_id] = [dict_mention]

    return dict_mentions

# Deprecated (this logic has been moved to the RelDisambLinker)
def rank_candidates(rel_json: dict, wk_cands: dict) -> dict:
    """
    Rank the candidates for each mention in the provided JSON data.

    Arguments:
        rel_json (dict): The JSON data containing articles and mention
            information.
        wk_cands (dict): Dictionary of Wikidata candidates for each mention.
        mentions_to_wikidata (dict): Dictionary mapping mentions to Wikidata
            entities.

    Returns:
        A new JSON dictionary with ranked candidates for each mention.
    """
    new_json = dict()
    for article in rel_json:
        new_json[article] = []
        for mention_dict in rel_json[article]:
            cands = []
            tmp_cands = []
            max_cand_freq = 0

            # TODO: get the ranking method from wk_cands.
            default = MentionCandidates(mention_dict["mention"], "TODO", "reldisamb", list())
            linker_cands = wk_cands.get(mention_dict["mention"], default)

            if not isinstance(linker_cands, MentionCandidates):
                raise ValueError(f"Expected MentionCandidates instance. Found: {type(linker_cands)}")

            # NOTE: mentions_to_wikidata here is the absolute link frequency data.

            for m in linker_cands.links:
                # DeezyMatch confidence score (cosine similarity):
                cand_selection_score = m.string_match.string_similarity
                # For each Wikidata candidate:
                for wikidata_link in m.wikidata_links:
                    wqid = wikidata_link.wqid
                    # Mention-to-wikidata absolute relevance:
                    # Here we assume that wikidata_link is a RelDisambLink instance:
                    qcrlv_score = wikidata_link.freq
                    if qcrlv_score > max_cand_freq:
                        max_cand_freq = qcrlv_score
                    qcm2w_score = wikidata_link.normalized_score
                    # Average of CS conf score and mention2wiki norm relv:
                    if cand_selection_score:
                        qcm2w_score = (qcm2w_score + cand_selection_score) / 2
                    tmp_cands.append((wqid, qcrlv_score, qcm2w_score))

            # Append candidate and normalized score weighted by candidate selection conf:
            for cand in tmp_cands:
                qc_id = cand[0]
                # Normalize absolute mention-to-wikidata relevance by entity:
                qc_score_1 = cand[1] / max_cand_freq
                # Candidate selection confidence:
                qc_score_2 = cand[2]
                # Averaged relevances and normalize between 0 and 0.9:
                qc_score = ((qc_score_1 + qc_score_2) / 2) * 0.9
                cands.append([qc_id, round(qc_score, 3)])
            # Sort candidates and normalize between 0 and 1, and so they add up to 1.
            cands = sorted(cands, key=lambda x: (x[1], x[0]), reverse=True)

            mention_dict["candidates"] = cands
            new_json[article].append(mention_dict)
    return new_json


def add_publication(
    rel_json: dict, publname: Optional[str] = "", publwqid: Optional[str] = ""
) -> dict:
    """
    Add publication information to the provided JSON data.

    Arguments:
        rel_json (dict): The JSON data containing articles and mention
            information.
        publname (str, optional): The name of the publication. Defaults to an
            empty string.
        publwqid (str, optional): The Wikidata ID of the publication. Defaults
            to an empty string.

    Returns:
        A new JSON dictionary with the added publication information.
    """
    new_json = rel_json.copy()
    for article in rel_json:
        place = publname
        place_wqid = publwqid
        if article != "linking":
            place = rel_json[article][0].get("place", publname)
            place_wqid = rel_json[article][0].get("place_wqid", publwqid)
        preffix_sentence = "This article is published in "
        sentence = preffix_sentence + place + "."
        dict_publ = {
            "mention": place,
            "sent_idx": 0,
            "sentence": sentence,
            "gold": [place_wqid],
            "ngram": place,
            "context": ["", ""],
            "pos": len(preffix_sentence),
            "end_pos": len(preffix_sentence + sentence),
            "candidates": [[place_wqid, 1.0]],
            "place": place,
            "place_wqid": place_wqid,
            "ner_label": "LOC",
        }
        new_json[article].append(dict_publ)
    return new_json


def prepare_rel_trainset(
    df: pd.DataFrame,
    rel_params,
    ranker: ranking.Ranker,
    linker,
    dsplit: str,
) -> dict:
    """
    Prepare the data for training and testing a REL disambiguation model.

    This function takes as input a pandas DataFrame (`df`) containing the
    dataset generated in the ``experiments/prepare_data.py`` script, along
    with a Linking object (``linker``) and a Ranking object (``ranker``).
    It prepares the data in the format required to train and test a REL
    disambiguation model, using the candidates from the ranker.

    Arguments:
        df (pandas.DataFrame): The pandas DataFrame containing the prepared
            dataset.
        rel_params (dict): Dictionary containing the parameters for performing
            entity disambiguation using the ``reldisamb`` approach.
        mentions_to_wikidata (dict): Dictionary mapping mentions to Wikidata
            entities, with counts.
        ranker (geoparser.ranking.Ranker): The Ranking object.
        dsplit (str): The split identifier for the data (e.g., ``"train"``,
            ``"test"``).

    Returns:
        The prepared data in the format of a JSON dictionary.

    Note:
        This function stores the formatted dataset as a JSON file.
    """
    rel_json = prepare_initial_data(df)
    sentence_mentions = {k: SentenceMentions.from_list(rel_json[k]) for k in rel_json.keys()}

    sentence_candidates = list()
    for k in rel_json.keys():
        matches = [ranker.run(mention) for mention in sentence_mentions[k].mentions]
        candidates = [linker.run(m, rel_json[k][0]["place_wqid"], rel_json[k][0]["place"]) for m in matches]
        sentence_candidates.append(SentenceCandidates(sentence_mentions[k].sentence, candidates))

    # Get interim predictions (i.e. without applying the REL model).
    predictions = [linker.disambiguate([scs], apply_rel=False) for scs in sentence_candidates]
    training_predictions = [TrainingPredictions(p.sentence_candidates) for p in predictions]

    trainset = {k: p.as_list(rel_params["with_publication"]) 
                for k, p in zip(rel_json.keys(), training_predictions)}

    ## TO DO
    with open(
        os.path.join(rel_params["data_path"], "rel_{}.json").format(dsplit),
        "w",
    ) as f:
        json.dump(trainset, f)

    return trainset
