name: Continuous integration

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install -r requirements.txt
    - name: Run code
      run: |
        $CONDA/bin/python processing.py
        $CONDA/bin/python preprocessing/wikipediaprocessing/extract_freq_and_pages.py -t
        $CONDA/bin/python preprocessing/wikipediaprocessing/aggregate_all_counts.py -t
        
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest 
