name: Continuous integration

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install -r requirements.txt
    - name: Test with pytest
      run: |
        $CONDA/bin/python process_data.py
        $CONDA/bin/pytest 
