name: Continuous integration

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.7
    - name: Install Poetry
        uses: snok/install-poetry@v1.1.7
      run: |
        cd toponym-resolution
        poetry install

    - name: Test with pytest
      run: |
        $CONDA/bin/python processing.py
        $CONDA/bin/pytest 
